### ISSUE TITLE
Contao 4: Error 500 after composer installation

### ISSUE THREAD

**Issue by k-webdesign** [codefog/contao-elements-filter#2]
Hi Kamil,

after the installation via Contao Manager (4.4.26) I get an error 500 🤔
<img width="1304" alt="screenshot 2018-10-04 15 46 50" src="https://user-images.githubusercontent.com/4130440/46478373-1fd48c80-c7ed-11e8-8fe8-5b1a80a80a47.png">

**Comment by qzminski** [comment]
Can you try to install `dev-develop` branch and see if that fixes your problem?

**Comment by k-webdesign** [comment]
Frontend works, Backend works again until I click the pen to edit any article, then I get:
<img width="1139" alt="screenshot 2018-10-04 20 39 28" src="https://user-images.githubusercontent.com/4130440/46495398-9b4a3400-c815-11e8-8d69-88f353b91c21.png">

**Comment by qzminski** [comment]
That should be fixed in b2105b2. Can you update the `dev-develop` again before I release the stable version please?

**Comment by do-while** [comment]
I have the same problem in Contao 4.4.32.
with the dev-develop branch it is Ok, no more errors

**Comment by qzminski** [comment]
Thanks @do-while for confirmation, I have just released 1.1.0.
